CODE OF CONDUCT.md
CONTRIBUTIONS GUIDE.md
README.md

Added Contribution Guide, Code Of Conduct & Update Readme for better understanding the project and contribution

Added Some Documentation Files

---

Components/LandingNav.tsx

Description:
This pull request resolves issue #25 
The pull request introduces an underline hover effect with a smooth transition to the navigation links, significantly improving the user experience and enhancing the overall UI. 
updated navigation links  : 
Please review and merge this pull request to incorporate the hover effect into the project.

improved hover effect of navigation links

---

pages/signup.tsx

I have resolved the issue of connecting firebase when clicked over the continue with Google buttonfor Sign up purpose and also have attached handler for SignUp Button.
I have also redirected the user to dashboard after signing in.
All this under #16 
Please review and merge!

Linked firebase to continue with Google option

---

pages/youtube.tsx

I have done it. Please accept the PR.
Thanks

Function Based Component.

---

Components/LandingNav.tsx

closes #49 
@PiyushKalyanpy I have removed package.json commits, Kindly Review.

(#49) Border radius added to navbar hover [GSSOC'23]

---

Components/LandingFooter.tsx

I have removed all the unnecessary files as you said and only added required files . 
did all as you said . 
**Before-:**
After-:
can u please give me GSSOC'23 label.

PR for issue#29

---

Components/LandingNav.tsx

redirection to homepage

---

Components/LandingThreeSecond.tsx

1. I have added the anchor tags in the Link element 
2. I have also made the Contributors Git-Hub links open in new tab making the user experience much better.
Additionally I have added the alternate text attribute in the contributors images.
3. And I have removed the gitignore changes

Added anchor tags in LandingThreeSecond and Removed the gitignore changes

---

Components/LandingFooter.tsx

Now, one doesn't need to change the year when it changes.
Successfully, implemented it without any conflict. Please do merge it.

Made the year in the footer dynamic.

---

Components/LandingNav.tsx

Conflicts of PR ,  Fixed : issue #17 #120 have been solved .
https://github.com/PiyushKalyanpy/GyanaGuru/assets/85991449/3e9e8486-f5d1-41ce-b76a-18295e880e95

New PR : issue #17

---

Components/LandingNav.tsx

<br>
Fixes/Closes: #199 
https://github.com/PiyushKalyanpy/GyanaGuru/assets/115401171/c1ee9e02-7759-4c96-ad53-e5d1db7dac14

Fixed bug for dark theme in nav bar

---

styles/globals.css

Closes : #270 
- Added custom scrollbar with track, thumb and root color property
- Added border-radius and color hover effect on hover and smooth transition
- Looks visually appealing in both dark and light themes
https://github.com/PiyushKalyanpy/GyanaGuru/assets/115401171/e3ed662d-7151-4bc3-a433-fab848c64ed9

Feature : Added custom scrollbar

---

Components/LandingFooter.tsx

- The goal of this PR is to add `aria-label` attributes for the social media anchor elements on `footer`.
- This helps to improve the accessibility of our Application and makes it to be used by any type of disabled peoples who relay on screen readers
- This PR Fixes/Closes: #224 
- @PiyushKalyanpy

💡 FEAT: ADD ARIA-LABELS FOR SOCIAL MEDIA ANCHOR ELEMENTS

---

CONTRIBUTIONS GUIDE.md

Updated Contribution guidelines for cloning and making pr's

Update CONTRIBUTIONS GUIDE.md

---

Components/WhyChooseUs.tsx

- Fixed the unconventional highlight in the dark mode in various sections of the websites(like Why Choose Us section on hovering).
Issue No #178 
https://github.com/PiyushKalyanpy/GyanaGuru/issues/178

Fixing the un-conventional highlight in dark mode in various sections of the websites

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature.yml

Added the checkboxes in issues temp

---

Components/LandingPage/WhyChooseUs.tsx

fixed issue #313 
changed color while hovering on cards in why choose section.

Changed hover color on cards

---

Components/RightSideBar/Calendar.tsx
Components/RightSideBar/IndividualDate.tsx
Components/RightSideBar/Notes.tsx
Components/RightSideBar/RightSideBar.tsx

Issue:#322:The right sidebar in the dashboard is now supporting a dark theme.
Before
After
@PiyushKalyanpy I want to contribute under gssoc23

#322-Right sidebar Dark Mode issue resolved

---

Components/LandingPage/LandingContact.tsx

Fixes/Closes: #287 
-   store user data from contact form
- remove formsubmit.co
- added firebase realtime database
- changes in Landingcontact.tsx file

send email through contact form using firebase realtime database [GSSOC'23] 

---

components/landing/LandingThreeGrid.tsx

Minor fix:  'provides' changed to 'provide'
Fixes/Closes: <issue/link>
Please provide a brief description of the purpose and goals of this pull request.
- High-level overview of the changes introduced.
- Step-by-step breakdown of the implementation, if applicable.
Include relevant screenshots or GIFs demonstrating the changes, especially for UI-related updates.
I have closed the previous PR #447, which have unknown package.json conflicts.
**_Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it._**

Issue #444 fixed 

---

.npmrc
package.json

The following changes have been done
1) .npmrc file added
2) npm version has been set in package.json
as per Issue #413

Enforce npm version

---

.prettierignore
.prettierrc
package.json

1) .prettierrc file added
2) .prettierignore file added
3) prettier has been added to package.json
as per Issue #415 
Note- please use npm run prettier --write  to format the codebase according to the rules

Prettier rules added

---

components/landing/LandingThreeGrid.tsx

Closes: #498
Fixing cards size in LandingThreeGrid component in small devices.
Include relevant screenshots or GIFs demonstrating the changes, especially for UI-related updates.

fixing cards size in LandingThreeGrid component

---

pages/index.tsx

Fixes/Closes: #484 
- Added meta tags like meta title, keywords, language, revisit-after, author, robots.

Added meta tags

---

components/cards/WhyChooseGyanGuruCard.tsx
components/landing/LandingFooter.tsx
components/landing/LandingNav.tsx
data/about_us.json
data/about_why_choose.json
pages/static/about-us.tsx

Closes: #489
The purpose of this PR is to apply the new design to the About Us page, providing an improved visual experience for users. In order to achieve this, the code for the About Us page has been modified, and a new card component, `WhyChooseGyanGuruCard.tsx`, has been created specifically for the "Why Choose GyanGuru" section. This component can be found in the `components/card` directory. Additionally, a component named `HeadingParagraph.tsx` has been utilized for rendering the mission and vision section.
- Made code modifications to the About Us page to align it with the new design.
- Updated the content and data in the `about_us.json` file according to the new design.
- Created a new data file named `about_why_choose.json` to accommodate the "Why Choose GyanGuru" section.
- …

Implementing New Design for the About Us Page

---

.github/workflows/lock.yml

Fixes/Closes: #469 
Added github action workflow to lock new issues.
- `.github/workflows/lock.yml`
What sort of change have you made:
Please review this PR
Thanks.

feat: add github action to lock new issues

---

pages/index.tsx

Closes: #517 
Fixing the position of navbar by changing initial value of showPopup useState from `0` to `false`.

fixing navbar position

---

components/landing/LandingFooter.tsx
components/landing/LandingNav.tsx
next.config.js

Fixes/Closes: #507 
-I have used async rewrite feature of NextJS to make the route.
**Before**
**After**
Include any additional information or context that might be helpful for the reviewers.
**_Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it._**

fix:Fixes Routing

---

pages/login.tsx

Updating the router route from /courses to /dashboard on the login page

---

src/components/landing/LandingThreeSecond.tsx

Closes: #548 
Please provide a brief description of the purpose and goals of this pull request.
- Removed target attribute.

removing target="_blank" from the anchor tag

---

src/styles/globals.css

Issue #554 fixed

---

src/components/landing/WhyChooseUs.tsx

Closes: #520 
Please provide a brief description of the purpose and goals of this pull request.
- made changes in grid-cols.

making WhyChooseUs section responsive

---

src/components/landing/LandingNav.tsx

This pull request addresses an issue with the navigation links in the website's navbar on the "About" page, which results in inconsistent URL paths and prevents users from accessing the correct pages. Additionally, I have made some changes to the Tailwind CSS classes to address issues where the code is not working as expected.
Fixes/Closes: https://github.com/PiyushKalyanpy/GyanaGuru/issues/526
- Modified the code responsible for generating navigation links on the "About" page to use relative URLs instead of absolute URLs. This change ensures consistent URL paths when navigating to other pages.
- Identified and fixed the issues in the Tailwind CSS classes that were causing the code to not work as expected.
- Updated specific class names and configurations to ensure proper styling and …

Navbar link issue #526 fixed

---

src/components/landing/WhyChooseUs.tsx

Fixes/Closes: #608
closes #608
Please provide a brief description of the purpose and goals of this pull request.
- High-level overview of the changes introduced.
- Step-by-step breakdown of the implementation, if applicable.
Include relevant screenshots or GIFs demonstrating the changes, especially for UI-related updates.
Include any additional information or context that might be helpful for the reviewers.
**_Also if you are fixing the already made PR and the reviewer demands some change in it then, in each PR you have to mention the issue you have fixed in it._**

fix : Inconsistent border Radius in "Why Choose Us" Section
